name: Publish
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx surge . uhsmathclub.surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}